AWSTemplateFormatVersion: "2010-09-09"

Description: "[CloudFormation] [Utility] CodeBuild Notification Template"

Parameters:

  Key:
    Type: String
    Description: |
      The parameter key to place into parameter store.

Resources:

  TemplateParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref Key
      Type: String
      Value: !Base64 >
        #set($type = $input.path('$.type'))
        #set($detail = $input.path('$.detail'))
        #set($status = $detail['build-status'])
        #set($id = $detail['build-id'].split('/')[1])
        #set($project = $detail['project-name'])
        #set($stream = $id.split(':')[1])
        #set($phase = $detail['current-phase'])
        {
          "channel": "$context.channel",
          #if ($status == 'IN_PROGRESS' && $phase == 'SUBMITTED')
          "attachments": [
            {
              "author_name": "Build Status",
              "author_icon": "https://github.com/davidkelley/tai/raw/master/.github/images/tai.png",
              "title": "$context.title (${context.region})",
              "title_link": "https://${context.region}.console.aws.amazon.com/codebuild/home#/builds/$project/view",
              "color": "#2196F3",
              "text": "Build started at $detail['additional-information']['build-start-time']",
              "actions": [
                {
                  "type": "button",
                  "text": "View Status",
                  "url": "https://${context.region}.console.aws.amazon.com/codebuild/home#/builds/$id/view/new",
                  "style": "primary"
                },
                {
                  "type": "button",
                  "text": "View Logs",
                  "url": "https://${context.region}.console.aws.amazon.com/cloudwatch/home#logEventViewer:group=/aws/codebuild/$project;stream=$stream",
                  "style": "primary"
                }
              ]
            }
          ]
          #else
          "attachments": [
            {
              "author_name": "Build Status",
              "author_icon": "https://github.com/davidkelley/tai/raw/master/.github/images/tai.png",
              "title": "$context.title (${context.region})",
              "title_link": "https://${context.region}.console.aws.amazon.com/codebuild/home#/builds/$project/view",
              #if ($status == 'SUCCEEDED')
              "color": "good",
              "text": "Build <https://${context.region}.console.aws.amazon.com/codebuild/home#/builds/$id/view/new|#$detail['additional-information']['artifact']['sha256sum'].substring(0,8)> passed",
              #else
              "color": "danger",
              #set($phases = $detail['additional-information']['phases'])
              #foreach($phase in $phases)
              #if ($phase['phase-type'] && $phase['phase-status'] == 'FAILED')
              "text": "Build failed in phase '$phase['phase-type']' after $phase['duration-in-seconds'] seconds",
              "fields": [
                {
                  "title": "Error",
                  "value": "$phase['phase-context'][0]"
                }
              ],
              #end
              #end
              #end
              "actions": [
                {
                  "type": "button",
                  "text": "View Status",
                  "url": "https://${context.region}.console.aws.amazon.com/codebuild/home#/builds/$id/view/new",
                  "style": "primary"
                },
                {
                  "type": "button",
                  "text": "View Logs",
                  "url": "https://${context.region}.console.aws.amazon.com/cloudwatch/home#logEventViewer:group=/aws/codebuild/$project;stream=$stream",
                  "style": "primary"
                }
              ]
            }
          ]
          #end
        }
